### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ordokr** [asserdna/chatbot_workshop#2]
I followed the instructions but got this error

chatbot-workshop> [Thu Mar 01 2018 19:55:08 GMT+0000 (UTC)] INFO /var/discourse/chatbot_workshop/src/scripts/hubot.js is using deprecated documentation syntax
hi
chatbot-workshop> **functionEntities[functionName] is not a function**

How do I fix this?  

Thank you!

**Comment by eduardomoroni** [comment]
The error regarding hubot documentation syntaxe could bem fixes following
this example
https://github.com/data-gov/wheeljack/blob/master/src/scripts/hubot.js

It seems your applications is not finding some function.
Which version of node and npm até you using?


Em qui, 1 de mar de 2018 5:00 PM, halsuga <notifications@github.com>
escreveu:

**Comment by ordokr** [comment]
I copied the code from https://github.com/data-gov/wheeljack/blob/master/src/scripts/hubot.js to chatbot_workshop/src/scripts/hubot.js and still I receive the same error.

npm = 5.6.0
node = 9.6.1

What can I do?

**Comment by eduardomoroni** [comment]
Looking at you npm and node version your bot should've work.
Ok Then, do you have a WIT.AI Token, as an environment variable called `WIT_SERVER_TOKEN`?

**Comment by eduardomoroni** [comment]
if so try to change
```
exports.answer = async message => {
    const parsedMessage = await plnParser.message(message, {});
    const entities = parsedMessage.entities;
    try {
        return answerBasedOnEntities(entities).result;
    } catch ({ message }) {
        return message;
    }
};
```

to

```
exports.answer = async message => plnParser.message(message, {});
```

If still not working, do you have rush to get it done? 
We gonna elaborate a fully explained workshop on How to create an chatbot bot using wit.ai and hubot, in two weeks.
I'm out on vacations and I'm sorry for not having time now, it's good getting started this link
https://www.youtube.com/watch?v=c6R3EjMQ7H0

**Comment by ordokr** [comment]
Thank you for trying to help, I have the WIT.AI token in bin/hubot as

export WIT_SERVER_TOKEN="ABC123......."

I changed the code as you asked.. but got this error

chatbot-workshop> hi
chatbot-workshop> [Sat Mar 03 2018 18:07:30 GMT+0000 (UTC)] INFO Shell asked me to hi
[object Object]

**Comment by eduardomoroni** [comment]
The problem is that your function: 
exports.answer = async message => plnParser.message(message, {});
is returning an object, try to take a look on what plnParser.message(message, {}); is returning, then return a string.

**Comment by eduardomoroni** [comment]
Anyways, I think this is not an issue anymore.
If you have further questions, 
Let us know

**Comment by ordokr** [comment]
I tried the code you gave, but it didn't work.  I have found a good solution with dialogflow.com and that bot, rather than wit.ai.  Thank you anyhow!

**Comment by eduardomoroni** [comment]
Hey @halsuga,
We've prepared a [WIKI](https://github.com/asserdna/chatbot_workshop/wiki) to help people out.
This might be interesting to you, it's in Portuguese. I Hope Google Translate can help you with that.
